#!/bin/bash
# Restore Script for Ultra Fast Laser Spectroscopy

# Restore Script restores the backup of the data used by the lab.
# Since there is no data being used by Ultra Fast Laser Spectroscopy, 
# the script does nothing. 

# Usage of the script

# To use restore script, run the command
# ./scripts/restore
